const CONSTANTS = {
  USER_LOGIN_SUCCESS: 'User login Successfully',
  TODO_CREATED_SUCCESS: 'Created Todo successfully',
  TODO_DELETED_SUCCESS: 'Todo deleted successfully',
  TODO_UPDATED_SUCCESS: 'Todo updated successfully',
  POST_CREATED_SUCCESS: 'Created Post successfully',
  POST_DELETED_SUCCESS: 'Post deleted successfully',
  POST_UPDATED_SUCCESS: 'Post updated successfully',
  USER_CREATED_SUCCESS: 'User created successfully',
  LOGIN_SUCCESS: 'User login success',
  USER_SIGN_UP_SUCCESS: 'User sign up success',
  LOGOUT_SUCCESS: 'Logout success',
  SIGN_IN_TOKEN_FAILURE: 'Could not sign token',
  TOKEN_REQUIRED_FAILURE: 'Token is required, Please login again',
  TOKEN_VERIFY_FAILURE: 'Could not verify token',
  USER_NAME_REQUIRED_FAILURE: 'User name is required',
  EMAIL_REQUIRED_FAILURE: 'email is required',
  PASSWORD_REQUIRED_FAILURE: 'password is required',
  USER_NAME_OR_EMAILS_EXISTS_FAILURE: 'Username or email already exists',
  SIGN_UP_FAILURE: 'Something went wrong in signup',
  USERNAME_OR_PASSWORD_INCORRECT_FAILURE: 'User name or password incorrect',
  POST_TITLE_REQUIRED_FAILURE: 'Post "title" is required',
  POST_BODY_REQUIRED_FAILURE: 'Post "body" is required',
  TODO_DOES_NOT_EXIST: 'Todo document does not exist',
  POST_DOES_NOT_EXIST: 'Post document does not exist',
  UNAUTHORISED: 'Unauthorized, cannot perform this action',
  SOMETHING_WENT_WRONG: 'Something went wrong',
  REQUIRED_FAILURE: 'is required',
  TITLE_REQUIRED_FAILURE: 'Todo Title required',
};

export default CONSTANTS;
